// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEGebjXhcVAbS_JlNTWeYYusnv8zlyfBk',
    appId: '1:493939253680:web:dee693775c33d1ba1af675',
    messagingSenderId: '493939253680',
    projectId: 'refound-5eca5',
    authDomain: 'refound-5eca5.firebaseapp.com',
    storageBucket: 'refound-5eca5.firebasestorage.app',
    measurementId: 'G-KG0YF0VZTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVPXbNWyqVRkAGc17EezvMNOWCS5BZG7E',
    appId: '1:493939253680:android:ff691c0d7bd1855e1af675',
    messagingSenderId: '493939253680',
    projectId: 'refound-5eca5',
    storageBucket: 'refound-5eca5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwUz9cBPAEDWqndJNDNb3Cap5-RGbDBfw',
    appId: '1:493939253680:ios:e759c0c25a5655061af675',
    messagingSenderId: '493939253680',
    projectId: 'refound-5eca5',
    storageBucket: 'refound-5eca5.firebasestorage.app',
    iosBundleId: 'com.example.refound',
  );
}
